project "assimp"
    kind "StaticLib"
    cppdialect "C++11"
    staticruntime "on"
    language "C"

    targetdir (bindir .. "/Bin/" .. outputdir .. "/%{prj.name}")
    objdir (bindir .. "/Obj/" .. outputdir .. "/%{prj.name}")


    includedirs
    {
        "include",
        "code",
    }

    sysincludedirs
    {
        ".",
        "contrib/pugixml/src",
        "contrib/openddlparser/include",
        "contrib/unzip",
        "contrib/rapidjson/include",
        "contrib/zlib",
    }

    files
    {
        "code/**.cpp",
        "include/**.h",
        "contrib/zlib/**.c",

        -- "code/AssetLib/3DS/3DSConverter.cpp",
        -- "code/AssetLib/3DS/3DSExporter.cpp",
        -- "code/AssetLib/3DS/3DSLoader.cpp",
        -- "code/AssetLib/3MF/D3MFExporter.cpp",
        -- "code/AssetLib/3MF/D3MFImporter.cpp",
        -- "code/AssetLib/3MF/D3MFOpcPackage.cpp",
        -- "code/AssetLib/AC/ACLoader.cpp",
        -- "code/AssetLib/AMF/AMFImporter.cpp",
        -- "code/AssetLib/AMF/AMFImporter_Geometry.cpp",
        -- "code/AssetLib/AMF/AMFImporter_Material.cpp",
        -- "code/AssetLib/AMF/AMFImporter_Postprocess.cpp",
        -- "code/AssetLib/ASE/ASELoader.cpp",
        -- "code/AssetLib/ASE/ASEParser.cpp",
        -- "code/AssetLib/Assbin/AssbinExporter.cpp",
        -- "code/AssetLib/Assbin/AssbinFileWriter.cpp",
        -- "code/AssetLib/Assbin/AssbinLoader.cpp",
        -- "code/AssetLib/Assjson/json_exporter.cpp",
        -- "code/AssetLib/Assjson/mesh_splitter.cpp",
        -- "code/AssetLib/Assxml/AssxmlExporter.cpp",
        -- "code/AssetLib/Assxml/AssxmlFileWriter.cpp",
        -- "code/AssetLib/B3D/B3DImporter.cpp",
        -- "code/AssetLib/BVH/BVHLoader.cpp",
        -- "code/AssetLib/Blender/BlenderBMesh.cpp",
        -- "code/AssetLib/Blender/BlenderCustomData.cpp",
        -- "code/AssetLib/Blender/BlenderDNA.cpp",
        -- "code/AssetLib/Blender/BlenderLoader.cpp",
        -- "code/AssetLib/Blender/BlenderModifier.cpp",
        -- "code/AssetLib/Blender/BlenderScene.cpp",
        -- "code/AssetLib/Blender/BlenderTessellator.cpp",
        -- -- "code/AssetLib/C4D/C4DImporter.cpp",
        -- "code/AssetLib/COB/COBLoader.cpp",
        -- "code/AssetLib/CSM/CSMLoader.cpp",
        -- "code/AssetLib/Collada/ColladaExporter.cpp",
        -- "code/AssetLib/Collada/ColladaHelper.cpp",
        -- "code/AssetLib/Collada/ColladaLoader.cpp",
        -- "code/AssetLib/Collada/ColladaParser.cpp",
        -- "code/AssetLib/DXF/DXFLoader.cpp",
        -- "code/AssetLib/FBX/FBXAnimation.cpp",
        -- "code/AssetLib/FBX/FBXBinaryTokenizer.cpp",
        -- "code/AssetLib/FBX/FBXConverter.cpp",
        -- "code/AssetLib/FBX/FBXDeformer.cpp",
        -- "code/AssetLib/FBX/FBXDocument.cpp",
        -- "code/AssetLib/FBX/FBXDocumentUtil.cpp",
        -- "code/AssetLib/FBX/FBXExportNode.cpp",
        -- "code/AssetLib/FBX/FBXExportProperty.cpp",
        -- "code/AssetLib/FBX/FBXExporter.cpp",
        -- "code/AssetLib/FBX/FBXImporter.cpp",
        -- "code/AssetLib/FBX/FBXMaterial.cpp",
        -- "code/AssetLib/FBX/FBXMeshGeometry.cpp",
        -- "code/AssetLib/FBX/FBXModel.cpp",
        -- "code/AssetLib/FBX/FBXNodeAttribute.cpp",
        -- "code/AssetLib/FBX/FBXParser.cpp",
        -- "code/AssetLib/FBX/FBXProperties.cpp",
        -- "code/AssetLib/FBX/FBXTokenizer.cpp",
        -- "code/AssetLib/FBX/FBXUtil.cpp",
        -- "code/AssetLib/HMP/HMPLoader.cpp",
        -- -- "code/AssetLib/IFC/IFCBoolean.cpp",
        -- -- "code/AssetLib/IFC/IFCCurve.cpp",
        -- -- "code/AssetLib/IFC/IFCGeometry.cpp",
        -- -- "code/AssetLib/IFC/IFCLoader.cpp",
        -- -- "code/AssetLib/IFC/IFCMaterial.cpp",
        -- -- "code/AssetLib/IFC/IFCOpenings.cpp",
        -- -- "code/AssetLib/IFC/IFCProfile.cpp",
        -- -- "code/AssetLib/IFC/IFCReaderGen1_2x3.cpp",
        -- -- "code/AssetLib/IFC/IFCReaderGen2_2x3.cpp",
        -- -- "code/AssetLib/IFC/IFCReaderGen_4.cpp",
        -- -- "code/AssetLib/IFC/IFCUtil.cpp",
        -- "code/AssetLib/Irr/IRRLoader.cpp",
        -- "code/AssetLib/Irr/IRRMeshLoader.cpp",
        -- "code/AssetLib/Irr/IRRShared.cpp",
        -- "code/AssetLib/LWO/LWOAnimation.cpp",
        -- "code/AssetLib/LWO/LWOBLoader.cpp",
        -- "code/AssetLib/LWO/LWOLoader.cpp",
        -- "code/AssetLib/LWO/LWOMaterial.cpp",
        -- "code/AssetLib/LWS/LWSLoader.cpp",
        -- "code/AssetLib/M3D/M3DExporter.cpp",
        -- "code/AssetLib/M3D/M3DImporter.cpp",
        -- "code/AssetLib/M3D/M3DWrapper.cpp",
        -- "code/AssetLib/MD2/MD2Loader.cpp",
        -- "code/AssetLib/MD3/MD3Loader.cpp",
        -- "code/AssetLib/MD5/MD5Loader.cpp",
        -- "code/AssetLib/MD5/MD5Parser.cpp",
        -- "code/AssetLib/MDC/MDCLoader.cpp",
        -- "code/AssetLib/MDL/HalfLife/HL1MDLLoader.cpp",
        -- "code/AssetLib/MDL/HalfLife/UniqueNameGenerator.cpp",
        -- "code/AssetLib/MDL/MDLLoader.cpp",
        -- "code/AssetLib/MDL/MDLMaterialLoader.cpp",
        -- "code/AssetLib/MMD/MMDImporter.cpp",
        -- "code/AssetLib/MMD/MMDPmxParser.cpp",
        -- "code/AssetLib/MS3D/MS3DLoader.cpp",
        -- "code/AssetLib/NDO/NDOLoader.cpp",
        -- "code/AssetLib/NFF/NFFLoader.cpp",
        -- "code/AssetLib/OFF/OFFLoader.cpp",
        -- "code/AssetLib/Obj/ObjExporter.cpp",
        -- "code/AssetLib/Obj/ObjFileImporter.cpp",
        -- "code/AssetLib/Obj/ObjFileMtlImporter.cpp",
        -- "code/AssetLib/Obj/ObjFileParser.cpp",
        -- "code/AssetLib/Ogre/OgreBinarySerializer.cpp",
        -- "code/AssetLib/Ogre/OgreImporter.cpp",
        -- "code/AssetLib/Ogre/OgreMaterial.cpp",
        -- "code/AssetLib/Ogre/OgreStructs.cpp",
        -- "code/AssetLib/Ogre/OgreXmlSerializer.cpp",
        -- "code/AssetLib/OpenGEX/OpenGEXExporter.cpp",
        -- "code/AssetLib/OpenGEX/OpenGEXImporter.cpp",
        -- "code/AssetLib/Ply/PlyExporter.cpp",
        -- "code/AssetLib/Ply/PlyLoader.cpp",
        -- "code/AssetLib/Ply/PlyParser.cpp",
        -- "code/AssetLib/Q3BSP/Q3BSPFileImporter.cpp",
        -- "code/AssetLib/Q3BSP/Q3BSPFileParser.cpp",
        -- "code/AssetLib/Q3D/Q3DLoader.cpp",
        -- "code/AssetLib/Raw/RawLoader.cpp",
        -- "code/AssetLib/SIB/SIBImporter.cpp",
        -- "code/AssetLib/SMD/SMDLoader.cpp",
        -- "code/AssetLib/STEPParser/STEPFileEncoding.cpp",
        -- "code/AssetLib/STEPParser/STEPFileReader.cpp",
        -- "code/AssetLib/STL/STLExporter.cpp",
        -- "code/AssetLib/STL/STLLoader.cpp",
        -- "code/AssetLib/Step/StepExporter.cpp",
        -- "code/AssetLib/Terragen/TerragenLoader.cpp",
        -- "code/AssetLib/Unreal/UnrealLoader.cpp",
        -- "code/AssetLib/X/XFileExporter.cpp",
        -- "code/AssetLib/X/XFileImporter.cpp",
        -- "code/AssetLib/X/XFileParser.cpp",
        -- "code/AssetLib/X3D/X3DExporter.cpp",
        -- "code/AssetLib/X3D/X3DImporter.cpp",
        -- "code/AssetLib/XGL/XGLLoader.cpp",
        -- "code/AssetLib/glTF/glTFCommon.cpp",
        -- "code/AssetLib/glTF/glTFExporter.cpp",
        -- "code/AssetLib/glTF/glTFImporter.cpp",
        -- "code/AssetLib/glTF2/glTF2Exporter.cpp",
        -- "code/AssetLib/glTF2/glTF2Importer.cpp",

        -- "code/CApi/AssimpCExport.cpp",
        -- "code/CApi/CInterfaceIOWrapper.cpp",
        -- "code/Common/AssertHandler.cpp",
        -- "code/Common/Assimp.cpp",
        -- "code/Common/BaseImporter.cpp",
        -- "code/Common/BaseProcess.cpp",
        -- "code/Common/Bitmap.cpp",
        -- "code/Common/CreateAnimMesh.cpp",
        -- "code/Common/DefaultIOStream.cpp",
        -- "code/Common/DefaultIOSystem.cpp",
        -- "code/Common/DefaultLogger.cpp",
        -- "code/Common/Exceptional.cpp",
        -- "code/Common/Exporter.cpp",
        -- "code/Common/Importer.cpp",
        -- "code/Common/ImporterRegistry.cpp",
        -- "code/Common/PostStepRegistry.cpp",
        -- "code/Common/RemoveComments.cpp",
        -- "code/Common/SGSpatialSort.cpp",
        -- "code/Common/SceneCombiner.cpp",
        -- "code/Common/ScenePreprocessor.cpp",
        -- "code/Common/SkeletonMeshBuilder.cpp",
        -- "code/Common/SpatialSort.cpp",
        -- "code/Common/StandardShapes.cpp",
        -- "code/Common/Subdivision.cpp",
        -- "code/Common/TargetAnimation.cpp",
        -- "code/Common/Version.cpp",
        -- "code/Common/VertexTriangleAdjacency.cpp",
        -- "code/Common/ZipArchiveIOSystem.cpp",
        -- "code/Common/material.cpp",
        -- "code/Common/scene.cpp",
        -- "code/Common/simd.cpp",
        -- "code/Material/MaterialSystem.cpp",
        -- "code/PostProcessing/ArmaturePopulate.cpp",
        -- "code/PostProcessing/CalcTangentsProcess.cpp",
        -- "code/PostProcessing/ComputeUVMappingProcess.cpp",
        -- "code/PostProcessing/ConvertToLHProcess.cpp",
        -- "code/PostProcessing/DeboneProcess.cpp",
        -- "code/PostProcessing/DropFaceNormalsProcess.cpp",
        -- "code/PostProcessing/EmbedTexturesProcess.cpp",
        -- "code/PostProcessing/FindDegenerates.cpp",
        -- "code/PostProcessing/FindInstancesProcess.cpp",
        -- "code/PostProcessing/FindInvalidDataProcess.cpp",
        -- "code/PostProcessing/FixNormalsStep.cpp",
        -- "code/PostProcessing/GenBoundingBoxesProcess.cpp",
        -- "code/PostProcessing/GenFaceNormalsProcess.cpp",
        -- "code/PostProcessing/GenVertexNormalsProcess.cpp",
        -- "code/PostProcessing/ImproveCacheLocality.cpp",
        -- "code/PostProcessing/JoinVerticesProcess.cpp",
        -- "code/PostProcessing/LimitBoneWeightsProcess.cpp",
        -- "code/PostProcessing/MakeVerboseFormat.cpp",
        -- "code/PostProcessing/OptimizeGraph.cpp",
        -- "code/PostProcessing/OptimizeMeshes.cpp",
        -- "code/PostProcessing/PretransformVertices.cpp",
        -- "code/PostProcessing/ProcessHelper.cpp",
        -- "code/PostProcessing/RemoveRedundantMaterials.cpp",
        -- "code/PostProcessing/RemoveVCProcess.cpp",
        -- "code/PostProcessing/ScaleProcess.cpp",
        -- "code/PostProcessing/SortByPTypeProcess.cpp",
        -- "code/PostProcessing/SplitByBoneCountProcess.cpp",
        -- "code/PostProcessing/SplitLargeMeshes.cpp",
        -- "code/PostProcessing/TextureTransform.cpp",
        -- "code/PostProcessing/TriangulateProcess.cpp",
        -- "code/PostProcessing/ValidateDataStructure.cpp",
    }

    removefiles
    {
        -- "code/AssetLib/C4D/C4DImporter.cpp"
    }

    defines
    {
        "ASSIMP_BUILD_NO_EXPORT",
        "ASSIMP_BUILD_NO_3DS_IMPORTER",
        "ASSIMP_BUILD_NO_3MF_IMPORTER",
        "ASSIMP_BUILD_NO_AC_IMPORTER",
        "ASSIMP_BUILD_NO_AMF_IMPORTER",
        "ASSIMP_BUILD_NO_ASW_IMPORTER",
        "ASSIMP_BUILD_NO_B3D_IMPORTER",
        -- "ASSIMP_BUILD_NO_Blender_IMPORTER",
        "ASSIMP_BUILD_NO_BVH_IMPORTER",
        "ASSIMP_BUILD_NO_C4D_IMPORTER",
        "ASSIMP_BUILD_NO_COB_IMPORTER",
        "ASSIMP_BUILD_NO_Collada_IMPORTER",
        "ASSIMP_BUILD_NO_CSM_IMPORTER",
        "ASSIMP_BUILD_NO_DXF_IMPORTER",
        "ASSIMP_BUILD_NO_FBX_IMPORTER",
        "ASSIMP_BUILD_NO_GLTF_IMPORTER",
        "ASSIMP_BUILD_NO_GLTF_EXPORTER",
        "ASSIMP_BUILD_NO_HMP_IMPORTER",
        "ASSIMP_BUILD_NO_IFC_IMPORTER",
        -- "ASSIMP_BUILD_NO_lrr_IMPORTER",
        "ASSIMP_BUILD_NO_LWO_IMPORTER",
        "ASSIMP_BUILD_NO_LWS_IMPORTER",
        "ASSIMP_BUILD_NO_M3D_IMPORTER",
        "ASSIMP_BUILD_NO_MD2_IMPORTER",
        "ASSIMP_BUILD_NO_MD3_IMPORTER",
        "ASSIMP_BUILD_NO_MD4_IMPORTER",
        "ASSIMP_BUILD_NO_MD5_IMPORTER",
        "ASSIMP_BUILD_NO_MDC_IMPORTER",
        "ASSIMP_BUILD_NO_MDL_IMPORTER",
        "ASSIMP_BUILD_NO_MMD_IMPORTER",
        "ASSIMP_BUILD_NO_MS3D_IMPORTER",
        "ASSIMP_BUILD_NO_NDO_IMPORTER",
        "ASSIMP_BUILD_NO_NFF_IMPORTER",
        -- "ASSIMP_BUILD_NO_Obj_IMPORTER",
        -- "ASSIMP_BUILD_NO_Ogre_IMPORTER",
        "ASSIMP_BUILD_NO_OPENGEX_IMPORTER",
        -- "ASSIMP_BUILD_NO_Ply_IMPORTER",
        -- "ASSIMP_BUILD_NO_Q3BSP_IMPORTER",
        -- "ASSIMP_BUILD_NO_Q3D_IMPORTER",
        -- "ASSIMP_BUILD_NO_Raw_IMPORTER",
        -- "ASSIMP_BUILD_NO_SIB_IMPORTER",
        -- "ASSIMP_BUILD_NO_SMD_IMPORTER",
        -- "ASSIMP_BUILD_NO_STL_IMPORTER",
        -- "ASSIMP_BUILD_NO_TERRAGEN_IMPORTER",
        -- "ASSIMP_BUILD_NO_Unreal_IMPORTER",
        -- "ASSIMP_BUILD_NO_X_IMPORTER",
        -- "ASSIMP_BUILD_NO_X3D_IMPORTER",
        "ASSIMP_BUILD_NO_XGL_IMPORTER",
        "ASSIMP_BUILD_NO_IRR_IMPORTER",
        "ASSIMP_BUILD_NO_OFF_IMPORTER",
        "ASSIMP_BUILD_NO_PLY_IMPORTER",
        "ASSIMP_BUILD_NO_TFI_IMPORTER",
    }


    filter "configurations:Debug"
        runtime "Debug"
        symbols "on"

    filter "configurations:Release"
        runtime "Release"
        optimize "on"
